services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uvicorn src.main:app --host 0.0.0.0 --reload --port 8000
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/usr/src

  redis:
    image: redis:latest

  worker:
    build: .
    volumes:
      - .:/usr/src
    command: celery -A src.worker.celery worker
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
    depends_on:
      - app
      - redis

  database:
    image: library/postgres:alpine
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
