"""remove unique constraint id_on_website

Revision ID: 51eaa54b3cd7
Revises: ff722d04aebf
Create Date: 2024-08-31 07:10:47.024294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eaa54b3cd7'
down_revision: Union[str, None] = 'ff722d04aebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('titles_id_on_website_key', 'titles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('titles_id_on_website_key', 'titles', ['id_on_website'])
    # ### end Alembic commands ###
