"""added episode sources table

Revision ID: cf67d6852423
Revises: 51eaa54b3cd7
Create Date: 2024-09-01 13:55:14.359657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf67d6852423'
down_revision: Union[str, None] = '51eaa54b3cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column(
        'image_url', sa.String(), nullable=True))
    op.create_table('episode_sources',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('episode_id', sa.UUID(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('quality', sa.Integer(), nullable=True),
                    sa.Column('is_m3u8', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode_sources')
    op.drop_column('episodes', 'image_url')
    # ### end Alembic commands ###
