"""added en_name column to titles

Revision ID: ff722d04aebf
Revises: f67301975066
Create Date: 2024-08-27 08:17:57.348959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff722d04aebf'
down_revision: Union[str, None] = 'f67301975066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('en_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'en_name')
    # ### end Alembic commands ###
